# Generated by Django 6.0.2 on 2026-03-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxomesh_contrib_django", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemmodel",
            name="external_id",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
    ]
