# Generated by Django 6.0.2 on 2026-03-16 23:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taxomesh_contrib_django", "0006_item_relation_link_source_type_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxomeshDebugProxy",
            fields=[],
            options={
                "verbose_name": "Debug",
                "verbose_name_plural": "Debug",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("taxomesh_contrib_django.categorymodel",),
        ),
    ]
