"""How the command line reads its configuration and builds its service.

:func:`build` finds the path of ``taxomesh.toml``, lets ``TaxomeshService`` build the repository
that the file names, and returns a :class:`BuildResult` with the service and the facts that the
``--verbose`` block prints.

``CONFIG_KEYS`` and :func:`dump_config` serve ``--show-config``. That option prints the repository
configuration that ``taxomesh._config`` finds, the defaults included, and builds no repository and
no service.
"""

import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Final

from taxomesh import TaxomeshService
from taxomesh._config import SUPPORTED_REPO_TYPES, config_file
from taxomesh.adapters.repositories.django_repository import _USING_DEFAULT as _DJANGO_USING_DEFAULT
from taxomesh.adapters.repositories.django_repository import DJANGO_REPO_TYPE
from taxomesh.adapters.repositories.json_repository import DEFAULT_JSON_PATH
from taxomesh.adapters.repositories.yaml_repository import DEFAULT_YAML_PATH, YAML_REPO_TYPE
from taxomesh.exceptions import TaxomeshConfigError, TaxomeshRepositoryError
from taxomesh.ports.repository import TaxomeshRepositoryBase

# The names of the supported TOML settings, as dotted paths. dump_config reads its key names here.
CONFIG_KEYS: Final[list[str]] = ["repository.type", "repository.path", "repository.using"]


def dump_config(repo_type: str, repo_detail: str) -> str:
    """Return the effective configuration as an annotated TOML string.

    The output is valid TOML, which ``tomllib.loads()`` reads. Above each key, comments say what
    the key controls, the values that it accepts and its default. The key names come from
    ``CONFIG_KEYS``, so this function holds no key name as a literal.

    Args:
        repo_type: The repository type that the configuration selects, such as ``"yaml"``,
            ``"json"`` or ``"django"``.
        repo_detail: The path of the file for ``yaml`` and ``json``, or the database alias for
            ``django``.

    Returns:
        The TOML text, which ends with a newline.
    """
    _section, _type_key = CONFIG_KEYS[0].split(".")
    _, _path_key = CONFIG_KEYS[1].split(".")
    _, _using_key = CONFIG_KEYS[2].split(".")
    accepted = '", "'.join(SUPPORTED_REPO_TYPES)
    if repo_type == DJANGO_REPO_TYPE:
        detail_comment = (
            f'# The Django database alias: a key of the DATABASES setting.\n# Default: "{_DJANGO_USING_DEFAULT}"\n'
        )
        detail_line = f'{_using_key} = "{repo_detail}"\n'
    else:
        detail_comment = (
            f'# The path of the data file.\n# Default: "{DEFAULT_YAML_PATH}" (yaml) or "{DEFAULT_JSON_PATH}" (json)\n'
        )
        detail_line = f'{_path_key} = "{repo_detail}"\n'
    return (
        "# The taxomesh configuration in effect\n"
        "# Generated by: taxomesh --show-config\n"
        "# To write a config file, redirect this output: taxomesh --show-config > taxomesh.toml\n"
        "\n"
        f"[{_section}]\n"
        "\n"
        f"# The storage backend.\n"
        f'# Accepted values: "{accepted}"\n'
        f'# Default: "{YAML_REPO_TYPE}"\n'
        f'{_type_key} = "{repo_type}"\n'
        "\n" + detail_comment + detail_line
    )


@dataclass
class BuildResult:
    """What :func:`build` returns: the service, its repository and the config file.

    A command uses the service, and the ``--verbose`` block prints the other three fields.

    Attributes:
        service: The service, built from the configuration.
        repository: The repository of the service.
        config_file_path: The absolute path of the config file. The file need not exist.
        config_file_exists: ``True`` if the file at ``config_file_path`` existed when
            :func:`build` ran; ``False`` otherwise.
    """

    service: TaxomeshService
    repository: TaxomeshRepositoryBase
    config_file_path: Path
    config_file_exists: bool


def build(config_path: Path | None = None) -> BuildResult:
    """Find ``taxomesh.toml``, build the service that it configures, and return both.

    ``TaxomeshService`` builds the repository. On a configuration error or a repository error,
    this function prints the message to stderr and exits with status 1.

    Args:
        config_path: The path of the config file. When ``None``, ``taxomesh.toml`` in the working
            directory.

    Returns:
        The service, its repository, the absolute path of the config file, and whether that file
        exists.
    """
    resolved = config_file(config_path).resolve()
    config_file_exists = resolved.exists()
    try:
        svc = TaxomeshService(config_path=resolved)
    except (TaxomeshConfigError, TaxomeshRepositoryError) as exc:
        print(f"{exc}", file=sys.stderr)
        sys.exit(1)
    return BuildResult(
        service=svc,
        repository=svc.repository,
        config_file_path=resolved,
        config_file_exists=config_file_exists,
    )
