"""CLI configuration loading for taxomesh.

Resolves the taxomesh.toml config file path, delegates all repository
construction to TaxomeshService, and returns a BuildResult containing the
configured TaxomeshService and associated metadata for use by CLI commands.

Also provides CONFIG_KEYS, dump_config(), and _resolve_effective_config() for
the --show-config flag, which prints the effective configuration without
initialising any repository or service.
"""

import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path
from typing import Final

from taxomesh import TaxomeshService
from taxomesh.adapters.repositories.json_repository import DEFAULT_JSON_PATH, JSON_REPO_TYPE
from taxomesh.adapters.repositories.yaml_repository import DEFAULT_YAML_PATH, YAML_REPO_TYPE
from taxomesh.exceptions import TaxomeshConfigError, TaxomeshRepositoryError
from taxomesh.ports.repository import TaxomeshRepositoryBase

_CONFIG_FILENAME: Final[str] = "taxomesh.toml"

# Single source of truth for all supported TOML setting names (dotted path format).
CONFIG_KEYS: Final[list[str]] = ["repository.type", "repository.path"]


def dump_config(repo_type: str, repo_path: str) -> str:
    """Return the effective configuration as an annotated TOML string.

    The output is valid TOML parseable by ``tomllib.loads()``.  Every key is
    preceded by a comment block describing what it controls, accepted values,
    and its default.  Key names are derived from ``CONFIG_KEYS`` so this
    function never contains bare key-name string literals.

    Args:
        repo_type: The active repository type (e.g. ``"yaml"`` or ``"json"``).
        repo_path: The active repository data-file path.

    Returns:
        A valid TOML string terminated with a trailing newline.
    """
    _section, _type_key = CONFIG_KEYS[0].split(".")
    _, _path_key = CONFIG_KEYS[1].split(".")
    return (
        "# taxomesh effective configuration\n"
        "# Generated by: taxomesh --show-config\n"
        "# Tip: redirect to create a config file: taxomesh --show-config > taxomesh.toml\n"
        "\n"
        f"[{_section}]\n"
        "\n"
        f"# Controls the storage backend type.\n"
        f'# Accepted values: "{YAML_REPO_TYPE}", "{JSON_REPO_TYPE}"\n'
        f'# Default: "{YAML_REPO_TYPE}"\n'
        f'{_type_key} = "{repo_type}"\n'
        "\n"
        f"# Path to the repository data file.\n"
        f'# Default: "{DEFAULT_YAML_PATH}" (yaml) or "{DEFAULT_JSON_PATH}" (json)\n'
        f'{_path_key} = "{repo_path}"\n'
    )


def _resolve_effective_config(config_path: Path | None) -> tuple[str, str]:
    """Resolve the effective repository type and path from a TOML config file.

    Reads and merges the config file with built-in defaults without
    constructing ``TaxomeshService`` or performing any repository I/O.

    Args:
        config_path: Explicit path to ``taxomesh.toml``.  If ``None``,
            auto-discovers ``taxomesh.toml`` in the current working directory.

    Returns:
        A ``(repo_type, repo_path)`` tuple of strings.

    Raises:
        TaxomeshConfigError: If the config file exists but cannot be read or
            contains invalid TOML.
    """
    resolved = (config_path if config_path is not None else Path.cwd() / _CONFIG_FILENAME).resolve()
    if not resolved.exists():
        return (YAML_REPO_TYPE, str(DEFAULT_YAML_PATH))
    try:
        text = resolved.read_text(encoding="utf-8")
        data = tomllib.loads(text)
    except (tomllib.TOMLDecodeError, OSError) as exc:
        raise TaxomeshConfigError(str(exc)) from exc
    section: dict[str, object] = data.get("repository", {})
    repo_type = str(section.get("type", YAML_REPO_TYPE))
    if "path" in section:
        repo_path = str(section["path"])
    elif repo_type == JSON_REPO_TYPE:
        repo_path = str(DEFAULT_JSON_PATH)
    else:
        repo_path = str(DEFAULT_YAML_PATH)
    return (repo_type, repo_path)


@dataclass
class BuildResult:
    """Result returned by the CLI build() factory.

    Bundles the ready-to-use service, underlying repository adapter, and config
    file metadata so sub-commands can display verbose diagnostic information.

    Attributes:
        service: Fully configured TaxomeshService ready for use.
        repository: The underlying repository adapter instance.
        config_file_path: Absolute, resolved path to the TOML config file.
            The file may or may not exist on disk.
        config_file_exists: True if config_file_path existed on disk at the
            time build() was called; False otherwise.
    """

    service: TaxomeshService
    repository: TaxomeshRepositoryBase
    config_file_path: Path
    config_file_exists: bool


def build(config_path: Path | None = None) -> BuildResult:
    """Resolve taxomesh.toml and return a fully-configured BuildResult.

    Resolves the config file path and delegates repository construction to
    TaxomeshService. On configuration or repository errors, prints a message
    to stderr and exits with code 1.

    Args:
        config_path: Explicit path to taxomesh.toml. If None, resolves
            taxomesh.toml relative to the current working directory.

    Returns:
        BuildResult containing the TaxomeshService, repository adapter,
        absolute config file path, and a flag indicating whether the config
        file exists on disk.
    """
    resolved = (config_path if config_path is not None else Path.cwd() / _CONFIG_FILENAME).resolve()
    config_file_exists = resolved.exists()
    try:
        svc = TaxomeshService(config_path=resolved)
    except (TaxomeshConfigError, TaxomeshRepositoryError) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        sys.exit(1)
    return BuildResult(
        service=svc,
        repository=svc.repository,
        config_file_path=resolved,
        config_file_exists=config_file_exists,
    )
