"""Render the generated blocks of ``docs/cli.md`` and ``llms.txt``.

Each of the two pages holds one block between the ``BEGIN`` and ``END`` markers below, and the
prose around it is written by hand. ``docs/cli.md``'s block is rendered from the Typer application:
every global option and every command, with its synopsis and summary. ``llms.txt``'s block is
rendered from the ledger of public signatures, ``tests/surface/public_surface.txt``, together with
what the ledger does not cover: the constructor, the graph's read models, the rows and the errors.
``test_reference_pages.py`` fails when a committed block differs from its rendering.

After a change to the command line or to the public surface, regenerate both blocks::

    python -c "import sys; sys.path.insert(0, '.'); \\
        from tests.docs._reference import write_references; write_references()"

and read the diff before committing it.
"""

import dataclasses
import inspect
import re
import typing
from collections.abc import Iterator
from pathlib import Path

import click
import typer.main
from pydantic import BaseModel

import taxomesh
from taxomesh import (
    Category,
    CategoryNode,
    CategoryParentLink,
    Item,
    ItemParentLink,
    ItemRelationLink,
    ItemTagLink,
    RelatedItems,
    RepositoryInfo,
    Tag,
    TaxomeshError,
    TaxomeshGraph,
    TaxomeshInfo,
    TaxomeshService,
)
from taxomesh.adapters.cli.main import app
from taxomesh.contrib.api.errors import TaxomeshGraphTooLargeError
from tests.surface._surface import public_names, render_member, render_signature

REPO_ROOT = Path(__file__).resolve().parents[2]
CLI_PAGE = REPO_ROOT / "docs" / "cli.md"
LLMS_PAGE = REPO_ROOT / "llms.txt"
LEDGER = REPO_ROOT / "tests" / "surface" / "public_surface.txt"

BEGIN = "<!-- BEGIN GENERATED by tests/docs/_reference.py: edit the renderer, not this block -->"
END = "<!-- END GENERATED -->"

# The ledger's owners, each with the heading its lines go under, the prefix a caller writes before
# a member, and what the collections' shared generic parameters stand for: ``K`` is the key a
# member takes and ``T`` the row it returns.
_OWNERS: dict[str, tuple[str, str, dict[str, str]]] = {
    "TaxomeshService": ("TaxomeshService", "svc.", {}),
    "CategoryCollection": (
        "svc.categories: CategoryCollection",
        "svc.categories.",
        {"K": "CategoryRef", "T": "Category"},
    ),
    "ItemCollection": ("svc.items: ItemCollection", "svc.items.", {"K": "ItemRef", "T": "Item"}),
    "TagCollection": ("svc.tags: TagCollection", "svc.tags.", {"K": "TagRef", "T": "Tag"}),
    "TaxomeshRepositoryBase": (
        "TaxomeshRepositoryBase: the storage port, implemented only by a custom backend",
        "",
        {},
    ),
}

# The read models a caller holds without constructing, rendered member by member.
_READ_MODELS: tuple[type, ...] = (TaxomeshGraph, CategoryNode, RelatedItems)

# The rows, links and info models that a member returns, rendered one line each, with their fields.
_ROWS: tuple[type, ...] = (
    Category,
    Item,
    Tag,
    CategoryParentLink,
    ItemParentLink,
    ItemRelationLink,
    ItemTagLink,
    TaxomeshInfo,
    RepositoryInfo,
)

# A dotted module path in front of a name: ``collections.abc.`` in ``collections.abc.Sequence``.
_MODULE_PATH = re.compile(r"\b(?:[a-z_][a-z0-9_]*\.)+(?=[A-Za-z_])")


def generated_block(page_text: str) -> str:
    """Return what a page holds between its markers. A page holds exactly one pair."""
    assert page_text.count(BEGIN) == 1, "a page holds exactly one BEGIN marker"
    assert page_text.count(END) == 1, "a page holds exactly one END marker"
    return page_text.split(BEGIN, 1)[1].split(END, 1)[0].strip("\n")


def with_generated_block(page_text: str, block: str) -> str:
    """Return the page with the text between its markers replaced by ``block``."""
    head = page_text.split(BEGIN, 1)[0]
    tail = page_text.split(END, 1)[1]
    return f"{head}{BEGIN}\n{block}\n{END}{tail}"


def write_references() -> None:
    """Rewrite both pages' generated blocks from the code, leaving their prose as it is."""
    for page, block in ((CLI_PAGE, render_cli_reference()), (LLMS_PAGE, render_llms_reference())):
        page.write_text(with_generated_block(page.read_text(encoding="utf-8"), block), encoding="utf-8")


# --- docs/cli.md ------------------------------------------------------------------------------


def cli_root() -> click.Group:
    """The click group Typer builds from the application."""
    root = typer.main.get_command(app)
    assert isinstance(root, click.Group)
    return root


def _leaf_commands(group: click.Group, path: tuple[str, ...]) -> Iterator[tuple[tuple[str, ...], click.Command]]:
    """Yield every command under ``group`` that is not itself a group, in click's own order."""
    context = click.Context(group)
    for name in group.list_commands(context):
        command = group.get_command(context, name)
        assert command is not None
        if isinstance(command, click.Group):
            yield from _leaf_commands(command, (*path, name))
        else:
            yield (*path, name), command


def cli_command_paths() -> list[tuple[str, ...]]:
    """Every command of the application, as the words that name it: ``("item", "place-in")``."""
    return [path for path, _ in _leaf_commands(cli_root(), ())]


def _cell(text: str) -> str:
    """Escape a table cell's pipes, which Markdown would otherwise read as column breaks."""
    return text.replace("|", "\\|")


def _value(parameter: click.Parameter) -> str:
    """The placeholder for a parameter's value: its choices, or its type's name."""
    if isinstance(parameter.type, click.Choice):
        return "|".join(str(choice) for choice in parameter.type.choices)
    return parameter.type.name.upper()


def _usage(parameter: click.Parameter, *, bracketed: bool = True) -> str:
    """Spell one parameter as a synopsis does, in brackets when it may be left off."""
    if isinstance(parameter, click.Option):
        name = "/".join([parameter.opts[0], *parameter.secondary_opts])
        usage = name if parameter.is_flag else f"{name} {_value(parameter)}"
        if parameter.multiple:
            usage = f"{usage} ..."
    else:
        usage = parameter.human_readable_name
    return f"[{usage}]" if bracketed and not parameter.required else usage


def _summary(command: click.Command) -> str:
    """A command's help, first paragraph only, on one line."""
    return " ".join(inspect.cleandoc(command.help or "").split("\n\n")[0].split())


def render_cli_reference() -> str:
    """Render the global options and every command, as ``docs/cli.md``'s block holds them."""
    root = cli_root()
    lines = ["| Global option | Description |", "|---|---|"]
    for option in root.params:
        assert isinstance(option, click.Option)
        lines.append(f"| `{_cell(_usage(option, bracketed=False))}` | {_cell(option.help or '')} |")
    lines += ["", "| Command | Description |", "|---|---|"]
    for path, command in _leaf_commands(root, ()):
        synopsis = " ".join(["taxomesh", *path, *(_usage(parameter) for parameter in command.params)])
        lines.append(f"| `{_cell(synopsis)}` | {_cell(_summary(command))} |")
    return "\n".join(lines)


# --- llms.txt ---------------------------------------------------------------------------------


def _short(text: str) -> str:
    """Drop module paths and ``self``, leaving a signature as a caller reads it."""
    return _MODULE_PATH.sub("", text).replace("(self, ", "(").replace("(self)", "()")


def _ledger_lines(owner: str) -> list[str]:
    """The ledger's lines for one owner, each without the owner's name."""
    lines = LEDGER.read_text(encoding="utf-8").splitlines()
    return [line.removeprefix(f"{owner}.") for line in lines if line.startswith(f"{owner}.")]


def _render_owner(owner: str) -> list[str]:
    """One ledger owner's section: its heading, then each member as a caller spells it."""
    heading, prefix, generics = _OWNERS[owner]
    lines = [f"## {heading}"]
    if owner == "TaxomeshService":
        constructor = _short(render_signature(TaxomeshService.__init__)).removesuffix(" -> None")
        lines.append(f"TaxomeshService{constructor}")
    for line in _ledger_lines(owner):
        rendered = _short(line)
        for name, meaning in generics.items():
            rendered = re.sub(rf"\b{name}\b", meaning, rendered)
        lines.append(f"{prefix}{rendered}")
    return lines


def _field_annotation(annotation: object) -> str:
    """Render a field's type, seeing through a type alias and its validators to the type it names."""
    if isinstance(annotation, typing.TypeAliasType):
        annotation = annotation.__value__
    if typing.get_origin(annotation) is typing.Annotated:
        annotation = typing.get_args(annotation)[0]
    return annotation.__name__ if isinstance(annotation, type) else _short(str(annotation))


def _fields(cls: type) -> list[tuple[str, str]]:
    """A row's fields and their types, in declaration order."""
    if issubclass(cls, BaseModel):
        return [(name, _field_annotation(field.annotation)) for name, field in cls.model_fields.items()]
    if not dataclasses.is_dataclass(cls):
        return []
    return [(field.name, _field_annotation(field.type)) for field in dataclasses.fields(cls)]


def _render_read_model(cls: type) -> list[str]:
    """A read model's public fields and members, one line each."""
    fields = [(name, annotation) for name, annotation in _fields(cls) if not name.startswith("_")]
    lines = [f"{cls.__name__}.{name}: {annotation}" for name, annotation in fields]
    field_names = {name for name, _ in fields}
    return lines + [_short(render_member(cls, name)) for name in public_names(cls) if name not in field_names]


def _render_errors() -> list[str]:
    """The error tree, one line per family, each with its standard-library base."""
    exported = [getattr(taxomesh, name) for name in taxomesh.__all__]
    errors = [value for value in exported if isinstance(value, type) and issubclass(value, TaxomeshError)]
    errors = [error for error in errors if error is not TaxomeshError] + [TaxomeshGraphTooLargeError]
    lines = [f"TaxomeshError({', '.join(base.__name__ for base in TaxomeshError.__bases__)})"]
    for family in (error for error in errors if TaxomeshError in error.__bases__):
        bases = ", ".join(base.__name__ for base in family.__bases__)
        where = "" if family.__name__ in taxomesh.__all__ else f", in {family.__module__}"
        members = [error.__name__ for error in errors if error is not family and issubclass(error, family)]
        lines.append(f"{family.__name__}({bases}){where}" + (f": {', '.join(members)}" if members else ""))
    return lines


def render_llms_reference() -> str:
    """Render the public surface, as ``llms.txt``'s block holds it."""
    lines: list[str] = []
    for owner in ("TaxomeshService", "CategoryCollection", "ItemCollection", "TagCollection"):
        lines += _render_owner(owner)
    lines.append("## The graph and related items")
    for cls in _READ_MODELS:
        lines += _render_read_model(cls)
    lines.append("## Rows, all frozen")
    for cls in _ROWS:
        lines.append(f"{cls.__name__}({', '.join(f'{name}: {annotation}' for name, annotation in _fields(cls))})")
    lines.append("## Errors")
    lines += _render_errors()
    lines += _render_owner("TaxomeshRepositoryBase")
    return "\n".join(lines)
