"""Category domain model."""

from datetime import datetime
from typing import Annotated
from uuid import UUID, uuid4

from pydantic import Field, field_validator

from taxomesh.domain.constants import (
    AUDIT_EPOCH,
    DEFAULT_CATEGORY_EXTERNAL_ID,
    DEFAULT_DESCRIPTION,
    DEFAULT_VERSION,
    MAX_CATEGORY_NAME_LENGTH,
    MAX_DESCRIPTION_LENGTH,
    MAX_EXTERNAL_ID_STR_LENGTH,
    MAX_SLUG_LENGTH,
)
from taxomesh.domain.models.base import ModelBase, _build_str_repr
from taxomesh.domain.types import ExternalId, FrozenDict, Metadata, normalise_external_id


class Category(ModelBase):
    """A category row. A category can have parents and children, and items are placed in it.

    Attributes:
        category_id: The identifier, generated by ``create``.
        name: The display name, at most ``MAX_CATEGORY_NAME_LENGTH`` characters. ``__root__`` is
            reserved.
        description: Free text, ``""`` unless given. Only a category has one.
        enabled: ``False`` leaves the category out of listings, searches, ``roots()`` and the
            graph, at the default of their ``enabled`` filter.
        external_id: The key of the record of yours that the category stands for, stored as text
            and unique among categories; ``None`` when there is none.
        slug: A text key for URLs, unique among categories; ``""`` is no slug.
        metadata: Plain JSON, frozen all the way down.
        created_at: When ``create`` stored the row; the audit epoch, 1970-01-01 UTC, on a row
            stored without one.
        updated_at: When ``create`` or the latest ``update`` stored the row; the audit epoch on a
            row stored without one.
        version: 0 at ``create``, one higher on each ``update``. The repository assigns it, and
            compares it with the ``expected_version`` of a conditional update.
    """

    category_id: UUID = Field(default_factory=uuid4)
    name: Annotated[str, Field(max_length=MAX_CATEGORY_NAME_LENGTH)]
    description: Annotated[str, Field(max_length=MAX_DESCRIPTION_LENGTH)] = DEFAULT_DESCRIPTION
    enabled: bool = True
    external_id: Annotated[str | None, Field(max_length=MAX_EXTERNAL_ID_STR_LENGTH)] = DEFAULT_CATEGORY_EXTERNAL_ID
    slug: Annotated[str, Field(max_length=MAX_SLUG_LENGTH)] = ""
    metadata: Metadata = Field(default_factory=FrozenDict)
    created_at: datetime = Field(default=AUDIT_EPOCH)
    updated_at: datetime = Field(default=AUDIT_EPOCH)
    version: Annotated[int, Field(ge=0)] = DEFAULT_VERSION

    @field_validator("description", mode="before")
    @classmethod
    def _coerce_none_description(cls, v: object) -> object:
        """Store a ``None`` description as ``""``."""
        return "" if v is None else v

    @field_validator("external_id", mode="before")
    @classmethod
    def _coerce_external_id(cls, v: ExternalId) -> str | None:
        """Convert the external id through the one rule, so a model built here and a lookup agree."""
        return normalise_external_id(v)

    def __str__(self) -> str:
        return _build_str_repr(self.name, self.category_id, self.slug, self.external_id)
