"""Item domain model."""

from datetime import datetime
from typing import Annotated
from uuid import UUID, uuid4

from pydantic import Field, field_validator

from taxomesh.domain.constants import (
    AUDIT_EPOCH,
    DEFAULT_ITEM_EXTERNAL_ID,
    DEFAULT_VERSION,
    MAX_EXTERNAL_ID_STR_LENGTH,
    MAX_ITEM_NAME_LENGTH,
    MAX_SLUG_LENGTH,
)
from taxomesh.domain.models.base import ModelBase, _build_str_repr
from taxomesh.domain.types import ExternalId, FrozenDict, Metadata, normalise_external_id


class Item(ModelBase):
    """An item row. You place an item in categories, tag it, and relate it to other items.

    Attributes:
        item_id: The identifier, generated by ``create``.
        name: The display name, at most ``MAX_ITEM_NAME_LENGTH`` characters.
        external_id: The key of the record of yours that the item stands for, stored as text and
            unique among items; ``None`` when there is none.
        slug: A text key for URLs, unique among items; ``""`` is no slug.
        enabled: ``False`` leaves the item out of listings, searches and related reads, at the
            default of their ``enabled`` filter.
        metadata: Plain JSON, frozen all the way down.
        created_at: When ``create`` stored the row; the audit epoch, 1970-01-01 UTC, on a row
            stored without one.
        updated_at: When ``create`` or the latest ``update`` stored the row; the audit epoch on a
            row stored without one.
        version: 0 at ``create``, one higher on each ``update``. The repository assigns it, and
            compares it with the ``expected_version`` of a conditional update.
    """

    item_id: UUID = Field(default_factory=uuid4)
    name: Annotated[str, Field(max_length=MAX_ITEM_NAME_LENGTH)]
    external_id: Annotated[str | None, Field(max_length=MAX_EXTERNAL_ID_STR_LENGTH)] = DEFAULT_ITEM_EXTERNAL_ID
    slug: Annotated[str, Field(max_length=MAX_SLUG_LENGTH)] = ""
    enabled: bool = True
    metadata: Metadata = Field(default_factory=FrozenDict)
    created_at: datetime = Field(default=AUDIT_EPOCH)
    updated_at: datetime = Field(default=AUDIT_EPOCH)
    version: Annotated[int, Field(ge=0)] = DEFAULT_VERSION

    @field_validator("external_id", mode="before")
    @classmethod
    def _coerce_external_id(cls, v: ExternalId) -> str | None:
        """Convert the external id through the one rule, so a model built here and a lookup agree."""
        return normalise_external_id(v)

    def __str__(self) -> str:
        return _build_str_repr(self.name, self.item_id, self.slug, self.external_id)
