"""Tag domain model."""

from typing import Annotated
from uuid import UUID, uuid4

from pydantic import Field

from taxomesh.domain.constants import MAX_TAG_NAME_LENGTH
from taxomesh.domain.models.base import ModelBase, _build_str_repr
from taxomesh.domain.types import FrozenDict, Metadata


class Tag(ModelBase):
    """A tag row. A tag has a name, and you attach it to items.

    Attributes:
        tag_id: The identifier, generated by ``create``.
        name: The display name, at most ``MAX_TAG_NAME_LENGTH`` characters.
        metadata: Plain JSON, frozen all the way down.
    """

    tag_id: UUID = Field(default_factory=uuid4)
    name: Annotated[str, Field(max_length=MAX_TAG_NAME_LENGTH)]
    metadata: Metadata = Field(default_factory=FrozenDict)

    def __str__(self) -> str:
        return _build_str_repr(self.name, self.tag_id)
